# Generated by Django 3.0 on 2020-04-30 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, default='images/avatar.png', upload_to='profile_picture', verbose_name='Profile Picture')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Age')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('mothers_name', models.CharField(max_length=200, verbose_name="Mother's Name")),
                ('fathers_name', models.CharField(max_length=200, verbose_name="Father's Name")),
                ('contact_no', models.IntegerField(verbose_name='Contact No')),
                ('email', models.CharField(max_length=200, verbose_name='Email Address')),
                ('bio', models.TextField(max_length=500, verbose_name='Your Bio')),
                ('academic_level', models.CharField(choices=[('JHS', 'JHS'), ('SHS', 'SHS')], max_length=100, verbose_name='Academic Level')),
                ('program', models.CharField(choices=[('ABM', 'ABM'), ('GAS', 'GAS'), ('ICT', 'ICT'), ('STEM', 'STEM')], max_length=100, verbose_name='Program')),
                ('student_id', models.CharField(max_length=100, verbose_name='Student ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, verbose_name='Gender')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Year_Level', verbose_name='Section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
